### ISSUE TITLE
Size issues

### ISSUE THREAD

**Issue by NoozAbooz** [phoenixbyrd/TwisterOS#1]
Hello!
So on the website, I think dynamic page size was off because the TwisterOS logo is cut off and the page isn't stretched to fit. 
![image](https://user-images.githubusercontent.com/44128563/90032780-feac1500-dc7b-11ea-9d60-eaee59f5d65d.png)

**Comment by phoenixbyrd** [comment]
Thank you for pointing this out. Seeing as I'm new to web development I have come across a couple of guides that may help me out in fixing this issue. Give me time to read, learn, digest and apply to the site. In the mean time view the site in a maximized window while I sort dynamic issues out. :)

**Comment by mobilegmYT** [comment]
![image](https://user-images.githubusercontent.com/44128563/90066822-7cd3e000-dcab-11ea-8b58-07d3c142cb26.png)
(On mobile at least...)
