### ISSUE TITLE
Various dual monitor issues

### ISSUE THREAD

**Issue by Chulamin** [phoenixbyrd/TwisterOS#10]
Hi. I use two monitors f different resolutions and find that the primary monitor loses the desktop icons on reboot. Resetting the resolution brings them back. This does not happen with the same setup using Raspberry Pi O/S. Also, the two monitors in Twister set up vertically to each other rather than horizontally as they do in Raspberry Pi. This makes it awkward when moving between screens. Also, when using VNC which I frequently do, I can't completely zoom in to either screen as I can using Raspberry Pi. And again, they appear vertically to each other on the remote screen as they do locally.  Overall, I love the look, feel and options in Twister, but these issues make it difficult to use. Any comments or work arounds would be welcome.

**Comment by phoenixbyrd** [comment]
This is for website issues, please join discord for Twister OS support
