### ISSUE TITLE
[Suggestion] Make text look better for mobile?

### ISSUE THREAD

**Issue by NoozAbooz** [phoenixbyrd/TwisterOS#2]
![image](https://user-images.githubusercontent.com/44128563/90067179-f075ed00-dcab-11ea-8358-dfb37e681538.png)
If you can, I'd suggest moving the logo and menu button both to the right, and make a sign or something that says "turn landscape for faq section" and maybe make the 
![image](https://user-images.githubusercontent.com/44128563/90067315-2b782080-dcac-11ea-8eb2-66c8b0d59635.png)
look a little formatted and a little nicer. That should be all for mobile. :smiley:

**Comment by phoenixbyrd** [comment]
Mobile layout is good enough unless there are some major issues other than just not pretty enough text, or not enough pixels in X direction, etc. I don't expect a large mobile audience downloading and burning Twister via their phones. As such is the case, the mobile layout mainly exists only as a brief information piece, landscape mode people ... (most people at least) ... should know to turn their phones for a different view be it a desktop mode or a landscape targeted layout offering more. I have brought text and img elements in closer that this screenshot shows though to attempt to make it 'nicer looking'.
