### ISSUE TITLE
[SUGGESTION] Bottom header change?

### ISSUE THREAD

**Issue by NoozAbooz** [phoenixbyrd/TwisterOS#3]
Hello!
So for the bottom header on the main page It says "Box86, Pi Labs, Commander Pi". Currently TwisterOS has commander pi and dynamic wallpapers, so maybe change it to like "Jack477"? 
![image](https://user-images.githubusercontent.com/44128563/90347825-da3f9800-dfef-11ea-97f6-2847b3a6d280.png)

**Comment by phoenixbyrd** [comment]
I don't do the logo designs
