### ISSUE TITLE
shortcut keys not working:

### ISSUE THREAD

**Issue by RedHandSheppard** [phoenixbyrd/TwisterOS#6]
new here, sorry if this isn't the rite place to ask. why are the shortcut keys not working?
ctr alt t doesn't launch the terminal

**Comment by NoozAbooz** [comment]
You can't launch the terminal if you don't have it open already.

**Comment by SaylorMomo** [comment]
I have added an shortcut key definition in Keyboard settings in the tab Application shortcuts
And assigned CTRL+ALT+T to /usr/bin/X11/X11/x-terminal-emulator
This launches the terminal in the desired way.
