### ISSUE TITLE
Cannot find a way to enable single-click for desktop

### ISSUE THREAD

**Issue by sgbeal** [phoenixbyrd/TwisterOS#7]
Single-click-to-activate is available in the file manager via the Behavior preferences tab, but that setting apparently has no effect on the desktop, nor is there any relevant setting in the desktop preferences applet.

Please tell me there's a way to enable single-click on the desktop. i've been single-clicking everything since literally last millennium, and the inability to do so would make twister a *very hard absolutely no-way nope* for me.

:-?

**Comment by sgbeal** [comment]
It occurs to me now that this might only be the tickets for the website, not the project, in which case feel free to close this as not relevant. The only potentially relevant project-level link i see on the site is for discord, which i don't use.

**Comment by NoozAbooz** [comment]
Yea sorry but Discord is the only way to get support for now. You could also try commenting on a Pi Labs video. But discord is pretty easy to use.
